# Generated by Django 5.1.5 on 2025-01-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_user_post_name_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='default_name', max_length=25),
        ),
    ]
